local stub = require("cook_stub")

local function reload()
    package.loaded["cook_cc.toolchain"] = nil
    return require("cook_cc.toolchain")
end

describe("toolchain probe registration", function()
    before_each(function() stub.reset(); stub.install() end)

    it("registers cc:compiler:auto on require with no override", function()
        local tc = reload()
        tc.ensure_probe_registered()
        assert.same({ "cc:compiler:auto" }, stub.probe_keys())
    end)

    it("toolchain.set({compiler='clang++'}) selects cc:compiler:clang++", function()
        local tc = reload()
        tc.set({ compiler = "clang++" })
        tc.ensure_probe_registered()
        assert.same({ "cc:compiler:clang++" }, stub.probe_keys())
    end)

    it("get_probe_key reflects current override", function()
        local tc = reload()
        assert.equals("cc:compiler:auto", tc.get_probe_key())
        tc.set({ compiler = "g++" })
        assert.equals("cc:compiler:g++", tc.get_probe_key())
    end)

    it("get_compiler at execute-time reads from probe value store", function()
        stub.set_probe_value("cc:compiler:auto", { cxx = "g++", cc = "gcc" })
        local tc = reload()
        tc.ensure_probe_registered()
        assert.same({ cxx = "g++", cc = "gcc" }, tc.get_compiler())
    end)

    it("produce body string contains the override compiler name", function()
        local tc = reload()
        tc.set({ compiler = "clang++" })
        tc.ensure_probe_registered()
        local opts = stub.probe_opts("cc:compiler:clang++")
        assert.is_string(opts.produce)
        assert.matches("clang%+%+", opts.produce)
    end)

    it("set + merge_defaults preserve module-local state across reload boundary", function()
        local tc = reload()
        tc.set({ standard = "c++17", warnings = "strict" })
        tc.merge_defaults({ defines = { "A" } })
        assert.equals("c++17", tc.get_default_standard())
        assert.equals("strict", tc.get_warnings())
        assert.same({ "A" }, tc.get_defaults().defines)
    end)
end)
