local stub = require("cook_stub")

describe("toolchain", function()
    before_each(function()
        stub.reset(); stub.install()
        package.loaded["cook_cc.toolchain"] = nil
    end)

    it("detects compiler from PATH when cache is empty (g++ available)", function()
        stub.set_sh_handler("command -v g++", function() return "/usr/bin/g++\n" end)
        stub.set_sh_handler("command -v clang++", function() error("not found") end)
        local toolchain = require("cook_cc.toolchain")
        toolchain.rehydrate()
        local c = toolchain.get_compiler()
        assert.equals("g++", c.cxx)
        assert.equals("gcc", c.cc)
    end)

    it("prefers cached compiler when cache hit + binary present", function()
        local cached = { cxx = "clang++", cc = "clang" }
        cook.cache.set("compiler", cached)
        stub.set_sh_handler("command -v clang++", function() return "/usr/bin/clang++\n" end)
        local toolchain = require("cook_cc.toolchain")
        toolchain.rehydrate()
        assert.same(cached, toolchain.get_compiler())
    end)

    it("re-detects when cached compiler no longer present", function()
        cook.cache.set("compiler", { cxx = "old-g++", cc = "old-gcc" })
        stub.set_sh_handler("command -v old-g++", function() error("missing") end)
        stub.set_sh_handler("command -v g++", function() return "/usr/bin/g++\n" end)
        stub.set_sh_handler("command -v clang++", function() error("missing") end)
        local toolchain = require("cook_cc.toolchain")
        toolchain.rehydrate()
        assert.equals("g++", toolchain.get_compiler().cxx)
    end)

    it("cc.toolchain({compiler=...}) overrides detected compiler", function()
        local toolchain = require("cook_cc.toolchain")
        toolchain.set({ compiler = "clang++" })
        assert.equals("clang++", toolchain.get_compiler().cxx)
        assert.equals("clang", toolchain.get_compiler().cc)
    end)

    it("cc.toolchain({standard='c++17'}) sets default_standard", function()
        local toolchain = require("cook_cc.toolchain")
        toolchain.set({ standard = "c++17" })
        assert.equals("c++17", toolchain.get_default_standard())
    end)

    it("cc.toolchain({warnings='strict'}) sets warnings preset", function()
        local toolchain = require("cook_cc.toolchain")
        toolchain.set({ warnings = "strict" })
        assert.equals("strict", toolchain.get_warnings())
    end)

    it("merge_defaults appends additive list fields", function()
        local toolchain = require("cook_cc.toolchain")
        toolchain.merge_defaults({ defines = { "A" }, includes = { "/x" } })
        toolchain.merge_defaults({ defines = { "B" } })
        assert.same({ "A", "B" }, toolchain.get_defaults().defines)
        assert.same({ "/x" }, toolchain.get_defaults().includes)
    end)

    it("merge_defaults extra_cflags has no leading space on first call", function()
        local toolchain = require("cook_cc.toolchain")
        toolchain.merge_defaults({ extra_cflags = "-O2" })
        assert.equals("-O2", toolchain.get_defaults().extra_cflags)
        toolchain.merge_defaults({ extra_cflags = "-g" })
        assert.equals("-O2 -g", toolchain.get_defaults().extra_cflags)
    end)
end)
